### ISSUE TITLE
CollectionField: preventReadAction not defined when browsing to /mson-react/contacts

### ISSUE THREAD

**Issue by joshglenn** [redgeoff/mson-react#172]
So I just synced up my local mson-react and mson, and I'm getting this error.

Anyone else notice this problem?

```
base-component.js:290 Uncaught PropertyNotDefinedError: CollectionField: preventReadAction not defined
    at CollectionField._throwIfNotDefined (http://localhost:3000/mson-react/static/js/0.chunk.js:64162:15)
    at CollectionField._getIfDefined (http://localhost:3000/mson-react/static/js/0.chunk.js:64725:12)
    at CollectionField._get (http://localhost:3000/mson-react/static/js/0.chunk.js:64740:21)
    at CollectionField.getOne (http://localhost:3000/mson-react/static/js/0.chunk.js:64746:19)
    at CollectionField.getOne (http://localhost:3000/mson-react/static/js/0.chunk.js:68535:107)
    at http://localhost:3000/mson-react/static/js/0.chunk.js:64762:34
    at Array.forEach (<anonymous>)
    at CollectionField.get (http://localhost:3000/mson-react/static/js/0.chunk.js:64761:15)
    at new _temp (http://localhost:3000/mson-react/static/js/main.chunk.js:1157:46)
    at constructClassInstance (http://localhost:3000/mson-react/static/js/0.chunk.js:111650:22)
    at updateClassComponent (http://localhost:3000/mson-react/static/js/0.chunk.js:115798:9)
    at beginWork$1 (http://localhost:3000/mson-react/static/js/0.chunk.js:117545:20)
    at HTMLUnknownElement.callCallback (http://localhost:3000/mson-react/static/js/0.chunk.js:97706:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/mson-react/static/js/0.chunk.js:97755:20)
    at invokeGuardedCallback (http://localhost:3000/mson-react/static/js/0.chunk.js:97808:35)
    at beginWork$$1 (http://localhost:3000/mson-react/static/js/0.chunk.js:123146:11)
    at performUnitOfWork (http://localhost:3000/mson-react/static/js/0.chunk.js:122060:16)
    at workLoopSync (http://localhost:3000/mson-react/static/js/0.chunk.js:122036:26)
    at performSyncWorkOnRoot (http://localhost:3000/mson-react/static/js/0.chunk.js:121625:15)
    at http://localhost:3000/mson-react/static/js/0.chunk.js:109655:28
    at unstable_runWithPriority (http://localhost:3000/mson-react/static/js/0.chunk.js:150451:16)
    at runWithPriority$2 (http://localhost:3000/mson-react/static/js/0.chunk.js:109601:14)
    at flushSyncCallbackQueueImpl (http://localhost:3000/mson-react/static/js/0.chunk.js:109650:11)
    at flushSyncCallbackQueue (http://localhost:3000/mson-react/static/js/0.chunk.js:109638:7)
    at scheduleUpdateOnFiber (http://localhost:3000/mson-react/static/js/0.chunk.js:121063:13)
    at Object.enqueueSetState (http://localhost:3000/mson-react/static/js/0.chunk.js:111448:9)
    at _temp.push../node_modules/react/cjs/react.development.js.Component.setState (http://localhost:3000/mson-react/static/js/0.chunk.js:140548:20)
    at CollectionField._this.handleFieldChange (http://localhost:3000/mson-react/static/js/main.chunk.js:1149:21)
    at CollectionField.emit (http://localhost:3000/mson-react/static/js/0.chunk.js:46068:7)
    at CollectionField.emitChange (http://localhost:3000/mson-react/static/js/0.chunk.js:64098:12)
    at CollectionField._setPropertyAndEmitChange (http://localhost:3000/mson-react/static/js/0.chunk.js:64113:12)
    at CollectionField._setIfDifferent (http://localhost:3000/mson-react/static/js/0.chunk.js:64124:14)
    at CollectionField._setIfPropDefined (http://localhost:3000/mson-react/static/js/0.chunk.js:64170:12)
    at CollectionField._set (http://localhost:3000/mson-react/static/js/0.chunk.js:64249:14)
    at CollectionField._setIfDefined (http://localhost:3000/mson-react/static/js/0.chunk.js:64256:14)
    at http://localhost:3000/mson-react/static/js/0.chunk.js:64265:23
    at http://localhost:3000/mson-react/static/js/0.chunk.js:54349:11
    at baseForOwn (http://localhost:3000/mson-react/static/js/0.chunk.js:52312:20)
    at http://localhost:3000/mson-react/static/js/0.chunk.js:54304:14
    at forEach (http://localhost:3000/mson-react/static/js/0.chunk.js:57576:10)
    at CollectionField._setProps (http://localhost:3000/mson-react/static/js/0.chunk.js:64264:25)
    at CollectionField.set (http://localhost:3000/mson-react/static/js/0.chunk.js:64701:12)
    at CollectionField.set (http://localhost:3000/mson-react/static/js/0.chunk.js:70939:87)
    at CollectionField.set (http://localhost:3000/mson-react/static/js/0.chunk.js:68482:97)
    at CollectionField._emitDidCreate (http://localhost:3000/mson-react/static/js/0.chunk.js:64297:12)
    at CollectionField._emitCreate (http://localhost:3000/mson-react/static/js/0.chunk.js:64003:14)
    at http://localhost:3000/mson-react/static/js/0.chunk.js:64023:18
index.js:1 The above error occurred in the <_temp> component:
    in _temp (at field.js:35)
    in Field (at attach.js:104)
    in _temp (at form.js:124)
    in form (at form.js:137)
    in Form (at attach.js:104)
    in _temp (at inner-component.js:60)
    in InnerComponent (at component.js:53)
    in Component (at attach.js:104)
    in _temp (at app.js:558)
    in main (at app.js:587)
    in div (at app.js:584)
    in div (at app.js:583)
    in App (created by WithStyles(App))
    in WithStyles(App) (created by WithWidth(WithStyles(App)))
    in WithWidth(WithStyles(App)) (created by Context.Consumer)
    in withRouter(WithWidth(WithStyles(App))) (at attach.js:104)
    in _temp (at attach.js:104)
    in _temp (at app-container.js:47)
    in div (at app-container.js:46)
    in Router (created by BrowserRouter)
    in BrowserRouter (at app-container.js:41)
    in ThemeProvider (created by MuiThemeProvider)
    in MuiThemeProvider (at app-container.js:39)
    in AppContainer (at attach.js:104)
    in _temp (at render.js:16)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
console.<computed> @ index.js:1
react-dom.development.js:12212 Uncaught PropertyNotDefinedError: CollectionField: preventReadAction not defined
    at CollectionField._throwIfNotDefined (http://localhost:3000/mson-react/static/js/0.chunk.js:64162:15)
    at CollectionField._getIfDefined (http://localhost:3000/mson-react/static/js/0.chunk.js:64725:12)
    at CollectionField._get (http://localhost:3000/mson-react/static/js/0.chunk.js:64740:21)
    at CollectionField.getOne (http://localhost:3000/mson-react/static/js/0.chunk.js:64746:19)
    at CollectionField.getOne (http://localhost:3000/mson-react/static/js/0.chunk.js:68535:107)
    at http://localhost:3000/mson-react/static/js/0.chunk.js:64762:34
    at Array.forEach (<anonymous>)
    at CollectionField.get (http://localhost:3000/mson-react/static/js/0.chunk.js:64761:15)
    at new _temp (http://localhost:3000/mson-react/static/js/main.chunk.js:1157:46)
    at constructClassInstance (http://localhost:3000/mson-react/static/js/0.chunk.js:111650:22)
    at updateClassComponent (http://localhost:3000/mson-react/static/js/0.chunk.js:115798:9)
    at beginWork$1 (http://localhost:3000/mson-react/static/js/0.chunk.js:117545:20)
    at HTMLUnknownElement.callCallback (http://localhost:3000/mson-react/static/js/0.chunk.js:97706:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/mson-react/static/js/0.chunk.js:97755:20)
    at invokeGuardedCallback (http://localhost:3000/mson-react/static/js/0.chunk.js:97808:35)
    at beginWork$$1 (http://localhost:3000/mson-react/static/js/0.chunk.js:123146:11)
    at performUnitOfWork (http://localhost:3000/mson-react/static/js/0.chunk.js:122060:16)
    at workLoopSync (http://localhost:3000/mson-react/static/js/0.chunk.js:122036:26)
    at performSyncWorkOnRoot (http://localhost:3000/mson-react/static/js/0.chunk.js:121625:15)
    at http://localhost:3000/mson-react/static/js/0.chunk.js:109655:28
    at unstable_runWithPriority (http://localhost:3000/mson-react/static/js/0.chunk.js:150451:16)
    at runWithPriority$2 (http://localhost:3000/mson-react/static/js/0.chunk.js:109601:14)
    at flushSyncCallbackQueueImpl (http://localhost:3000/mson-react/static/js/0.chunk.js:109650:11)
    at flushSyncCallbackQueue (http://localhost:3000/mson-react/static/js/0.chunk.js:109638:7)
    at scheduleUpdateOnFiber (http://localhost:3000/mson-react/static/js/0.chunk.js:121063:13)
    at Object.enqueueSetState (http://localhost:3000/mson-react/static/js/0.chunk.js:111448:9)
    at _temp.push../node_modules/react/cjs/react.development.js.Component.setState (http://localhost:3000/mson-react/static/js/0.chunk.js:140548:20)
    at CollectionField._this.handleFieldChange (http://localhost:3000/mson-react/static/js/main.chunk.js:1149:21)
    at CollectionField.emit (http://localhost:3000/mson-react/static/js/0.chunk.js:46068:7)
    at CollectionField.emitChange (http://localhost:3000/mson-react/static/js/0.chunk.js:64098:12)
    at CollectionField._setPropertyAndEmitChange (http://localhost:3000/mson-react/static/js/0.chunk.js:64113:12)
    at CollectionField._setIfDifferent (http://localhost:3000/mson-react/static/js/0.chunk.js:64124:14)
    at CollectionField._setIfPropDefined (http://localhost:3000/mson-react/static/js/0.chunk.js:64170:12)
    at CollectionField._set (http://localhost:3000/mson-react/static/js/0.chunk.js:64249:14)
    at CollectionField._setIfDefined (http://localhost:3000/mson-react/static/js/0.chunk.js:64256:14)
    at http://localhost:3000/mson-react/static/js/0.chunk.js:64265:23
    at http://localhost:3000/mson-react/static/js/0.chunk.js:54349:11
    at baseForOwn (http://localhost:3000/mson-react/static/js/0.chunk.js:52312:20)
    at http://localhost:3000/mson-react/static/js/0.chunk.js:54304:14
    at forEach (http://localhost:3000/mson-react/static/js/0.chunk.js:57576:10)
    at CollectionField._setProps (http://localhost:3000/mson-react/static/js/0.chunk.js:64264:25)
    at CollectionField.set (http://localhost:3000/mson-react/static/js/0.chunk.js:64701:12)
    at CollectionField.set (http://localhost:3000/mson-react/static/js/0.chunk.js:70939:87)
    at CollectionField.set (http://localhost:3000/mson-react/static/js/0.chunk.js:68482:97)
    at CollectionField._emitDidCreate (http://localhost:3000/mson-react/static/js/0.chunk.js:64297:12)
    at CollectionField._emitCreate (http://localhost:3000/mson-react/static/js/0.chunk.js:64003:14)
    at http://localhost:3000/mson-react/static/js/0.chunk.js:64023:18
```

**Comment by MedinaGitHub** [comment]
i have the same problem

**Comment by redgeoff** [comment]
Please see the directions at https://github.com/redgeoff/mson#mson-demo
